version: '3.9'
services:
  movies:
    image: hanvitha/myapp:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3
  dth:
    image: hanvitha/recharge:v2
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: hanvitha/movies:v3
    ports:
      - "83:80"
    deploy:
      replicas: 3
    
