version: '3.8'
service:
  python:
    image: hanvitha/myapp
    ports:
      - "81:80"
    deploy:
      replicas: 3
  recharge: 
    image: hanvitha/recharge
    ports:
       - "82:80"
    deploy:
      replicas: 3
  movies:
    image: hanvitha/movies
    ports:
      - "83:80"
    deploy:
      replicas: 3
