version: '3.9'
services:
  movies:
    image: hanvitha/myapp:v1
    ports:
      - "84:80"
    deploy:
      replicas: 3
  dth:
    image: hanvitha/recharge:v2
    ports:
      - "85:80"
    deploy:
      replicas: 3
  recharge:
    image: hanvitha/movies:v3
    ports:
      - "86:80"
    deploy:
      replicas: 3
    
